# Generated by Django 4.2.26 on 2025-12-09 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_position_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollutionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pollution_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение загрязнения',
                'verbose_name_plural': 'Изображения загрязнения',
            },
        ),
        migrations.CreateModel(
            name='PollutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Тип загрязнения',
                'verbose_name_plural': 'Типы загрязнения',
            },
        ),
        migrations.CreateModel(
            name='Pollutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('images', models.ManyToManyField(related_name='pollutions', to='main.pollutionimage', verbose_name='Изображения')),
                ('pollution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pollutions', to='main.pollutiontype', verbose_name='Тип загрязнения')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_pollutions', to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение о загрязнении',
                'verbose_name_plural': 'Сообщения о загрязнении',
            },
        ),
    ]
