# Generated by Django 4.2.26 on 2025-12-09 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pollutionimage_pollutiontype_pollutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutions',
            name='images',
        ),
        migrations.AddField(
            model_name='pollutions',
            name='images',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pollutions', to='main.pollutionimage', verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
