# Generated by Django 4.2.26 on 2025-12-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_pollutions_images_pollutions_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutions',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона автора'),
        ),
    ]
