# Generated by Django 4.2.26 on 2025-12-09 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pollutions_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutions',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_pollutions', to=settings.AUTH_USER_MODEL, verbose_name='Взято в работу'),
        ),
    ]
