# Generated by Django 4.2.26 on 2025-12-09 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pollutions_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutions',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_pollutions', to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения'),
        ),
    ]
