# Generated by Django 4.2.26 on 2025-12-10 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_pollutions_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutions',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_pollutions', to=settings.AUTH_USER_MODEL, verbose_name='Завершил'),
        ),
        migrations.AddField(
            model_name='pollutions',
            name='completion_photo',
            field=models.ImageField(blank=True, null=True, upload_to='completion_photos/', verbose_name='Фото завершения'),
        ),
        migrations.AddField(
            model_name='pollutions',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AddField(
            model_name='user',
            name='completed_count',
            field=models.IntegerField(default=0, verbose_name='Количество завершенных работ'),
        ),
    ]
