# Generated by Django 4.2.26 on 2025-12-10 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_pollutions_completed_by_pollutions_completion_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Отвечено')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_admin_messages', to=settings.AUTH_USER_MODEL, verbose_name='От пользователя')),
            ],
            options={
                'verbose_name': 'Сообщение администрации',
                'verbose_name_plural': 'Сообщения администрации',
                'ordering': ['-created_at'],
            },
        ),
    ]
